apiVersion: v1
kind: Secret
metadata:
  name: analytics-secret
  namespace: togglemaster-analytics
type: Opaque
data:
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vU0VVLUFDQ09VTlQtSUQvdG9nZ2xlLW1hc3Rlci1ldmVudHM=
  AWS_DYNAMODB_TABLE: VG9nZ2xlTWFzdGVyQW5hbHl0aWNz
  AWS_REGION: dXMtZWFzdC0x
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-config
  namespace: togglemaster-analytics
data:
  PORT: "8005"
