apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: togglemaster-auth
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpDSEFOR0VfTUVAU0VVLVJEUy1IT1NULnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL2F1dGhfZGI=
  MASTER_KEY: Q0hBTkdFX01FX01BU1RFUl9LRVk=
