apiVersion: v1
kind: Secret
metadata:
  name: evaluation-secret
  namespace: togglemaster-evaluation
type: Opaque
data:
  REDIS_URL: cmVkaXM6Ly9TRVUtQ0FDSEUtSE9TVC5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk=
  SERVICE_API_KEY: dG1fa2V5X0NIQU5HRV9NRQ==
  AWS_SQS_URL: aHR0cHM6Ly9zcXMudXMtZWFzdC0xLmFtYXpvbmF3cy5jb20vU0VVLUFDQ09VTlQtSUQvdG9nZ2xlLW1hc3Rlci1ldmVudHM=
  AWS_REGION: dXMtZWFzdC0x
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-config
  namespace: togglemaster-evaluation
data:
  PORT: "8004"
  FLAG_SERVICE_URL: http://flag-service.togglemaster-flags.svc.cluster.local:8002
  TARGETING_SERVICE_URL: http://targeting-service.togglemaster-targeting.svc.cluster.local:8003
