apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: togglemaster-flags
  labels:
    app: flag-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          image: 740868193407.dkr.ecr.us-east-1.amazonaws.com/flag-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          envFrom:
            - secretRef:
                name: flag-secret
            - configMapRef:
                name: flag-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8002
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: togglemaster-flags
spec:
  selector:
    app: flag-service
  ports:
    - port: 8002
      targetPort: 8002
  type: ClusterIP
