apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-scaledobject
  namespace: togglemaster-analytics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-service
  minReplicaCount: 0
  maxReplicaCount: 4
  cooldownPeriod: 60
  pollingInterval: 15
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: https://sqs.us-east-1.amazonaws.com/740868193407/toggle-master-events
        queueLength: "5"
        awsRegion: "us-east-1"
        identityOwner: "operator"
