apiVersion: v1
kind: Secret
metadata:
  name: targeting-secret
  namespace: togglemaster-targeting
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly9wb3N0Z3JlczpDSEFOR0VfTUVAU0VVLVJEUy1IT1NULnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL3RhcmdldGluZ19kYg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-config
  namespace: togglemaster-targeting
data:
  AUTH_SERVICE_URL: http://auth-service.togglemaster-auth.svc.cluster.local:8001
  PORT: "8003"
