apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: toggle-master-cluster
  region: us-east-1

managedNodeGroups:
  - name: ng-standard
    instanceType: t3.small
    minSize: 1
    maxSize: 4
    desiredCapacity: 2
    volumeSize: 30
    privateNetworking: true
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        albIngress: true
        externalDNS: true
        imageBuilder: true